"""Add default value to assigned_at

Revision ID: 7e5dc9568b1b
Revises: 
Create Date: 2025-09-12 22:35:06.487996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5dc9568b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
       batch_op.add_column(sa.Column('assigned_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('phone_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
