import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle
import seaborn as sns
import matplotlib.pyplot as plt

# --- 1. Load the ENGINEERED Dataset ---
dataset_filename = 'exercise_coords_engineered.csv' # Changed to the new filename

try:
    df = pd.read_csv(dataset_filename)
except FileNotFoundError:
    print(f"Error: '{dataset_filename}' not found.")
    print("Please make sure you have run the feature_engineering.py script first.")
    exit()

print(f"Engineered dataset loaded successfully with {len(df)} samples.")

# --- 2. Prepare the data ---
# CORRECTED: This list MUST match the columns generated by your feature engineering script.
# We are assuming you removed the delta_angles features.
feature_cols = [
    'angle_torso_side_left', 'angle_torso_side_right', 'angle_torso_front', 'angle_neck',
    'angle_spine_hip_shoulder_left', 'angle_spine_hip_shoulder_right',
    'angle_left_elbow', 'angle_right_elbow', 'angle_left_shoulder_abduction',
    'angle_right_shoulder_abduction', 'angle_left_wrist', 'angle_right_wrist',
    'angle_left_hip', 'angle_right_hip', 'angle_left_knee', 'angle_right_knee',
    'angle_left_ankle', 'angle_right_ankle', 'angle_shoulder_hip_twist_left',
    'angle_shoulder_hip_twist_right', 'dist_shoulders', 'dist_hips',
    'dist_left_wrist_knee', 'dist_right_wrist_knee', 'dist_left_elbow_hip',
    'dist_right_elbow_hip', 'dist_left_ankle_wrist', 'dist_right_ankle_wrist',
    'dist_nose_hip', 'dist_y_l_wrist_shoulder', 'dist_y_r_wrist_shoulder',
    'dist_y_l_hip_knee', 'dist_y_r_hip_knee', 'dist_y_l_shoulder_hip',
    'dist_y_r_shoulder_hip', 'dist_y_l_ankle_heel', 'dist_y_r_ankle_heel',
    'dist_z_l_wrist_hip', 'dist_z_r_wrist_hip', 'dist_z_l_shoulder_hip',
    'dist_z_r_shoulder_hip', 'dist_z_nose_hip'
]

X = df[feature_cols]
y = df['class']

# --- Save feature names ---
feature_names = X.columns.tolist()
with open('feature_names.pkl', 'wb') as f:
    pickle.dump(feature_names, f)
print(f"✅ Feature names saved to 'feature_names.pkl'")
# --- END NEW ---

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# --- Scale the features for the Neural Network ---
print("\nScaling features for Neural Network training...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("✅ Feature scaler saved successfully as 'scaler.pkl'")

# --- 3. Build and Train the Neural Network (MLPClassifier) Model ---
print("\nTraining a Neural Network (MLPClassifier) model...")

mlp_model = MLPClassifier(
    hidden_layer_sizes=(100, 50),
    activation='relu',
    solver='adam',
    alpha=0.0001,
    batch_size='auto',
    learning_rate_init=0.001,
    max_iter=500,
    random_state=42,
    verbose=True
)

mlp_model.fit(X_train_scaled, y_train)
model = mlp_model
print("Model training complete.")

# --- 4. Evaluate the Model ---
print("\nEvaluating the new MLP model...")
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ MLP Model Accuracy on Engineered Data: {accuracy * 100:.2f}%")

# --- 5. Save the Trained Model ---
model_filename = 'exercise_model_mlp.pkl'
with open(model_filename, 'wb') as f:
    pickle.dump(model, f)

print(f"\n✅ New MLP model saved successfully as '{model_filename}'")

# --- 6. Visualize a Confusion Matrix ---
print("\nGenerating confusion matrix visualization...")
try:
    cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
    plt.figure(figsize=(15, 12))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=model.classes_, yticklabels=model.classes_)
    plt.title('Confusion Matrix for MLP Model')
    plt.ylabel('Actual Class')
    plt.xlabel('Predicted Class')
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig('confusion_matrix_mlp.png')
    print("✅ Confusion matrix saved as 'confusion_matrix_mlp.png'")
except Exception as e:
    print(f"Could not generate confusion matrix plot. Error: {e}")